# Generated by Django 6.0.2 on 2026-02-06 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=50, verbose_name='Nome do Status')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='OperatorProfessional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nome')),
                ('role', models.CharField(choices=[('Piloto', 'Piloto'), ('Bombeiro', 'Bombeiro'), ('Mecânico', 'Mecânico'), ('Médico', 'Médico'), ('Enfermeiro', 'Enfermeiro')], verbose_name='Cargo')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='professional.status')),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
            },
        ),
        migrations.CreateModel(
            name='OperatorFleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fleet_type', models.CharField(max_length=50, verbose_name='Tipo da Frota')),
                ('fleet_model', models.CharField(max_length=50, verbose_name='Modelo da Frota')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='professional.status')),
            ],
            options={
                'verbose_name': 'Frota',
                'verbose_name_plural': 'Frotas',
            },
        ),
    ]
