# Generated by Django 5.2.11 on 2026-03-06 00:25

import django.db.models.deletion
import professional.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0003_alter_operatorfleet_id_alter_operatorprofessional_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorfleet',
            name='status',
            field=models.ForeignKey(default=professional.models.get_default_status, on_delete=django.db.models.deletion.PROTECT, to='professional.status'),
        ),
        migrations.AlterField(
            model_name='operatorprofessional',
            name='status',
            field=models.ForeignKey(default=professional.models.get_default_status, on_delete=django.db.models.deletion.PROTECT, to='professional.status'),
        ),
    ]
