# Generated by Django 5.2.11 on 2026-03-06 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0004_alter_operatorfleet_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operatorfleet',
            options={'ordering': ['fleet_model'], 'verbose_name': 'Frota', 'verbose_name_plural': 'Frotas'},
        ),
        migrations.AlterModelOptions(
            name='operatorprofessional',
            options={'ordering': ['name'], 'verbose_name': 'Profissional', 'verbose_name_plural': 'Profissionais'},
        ),
    ]
