# Generated by Django 6.0.2 on 2026-02-06 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_date', models.DateField(verbose_name='Data da Missão')),
                ('description', models.TextField(max_length=1000, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('Em execução', 'Em execução'), ('Finalizada', 'Finalizada')])),
                ('operator_fleet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fleet_missions', to='professional.operatorfleet', verbose_name='Frota Alocada')),
            ],
            options={
                'verbose_name': 'Missão',
                'verbose_name_plural': 'Missões',
            },
        ),
    ]
