# Generated by Django 5.2.11 on 2026-02-27 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0002_alter_mission_id'),
        ('professional', '0002_alter_operatorfleet_id_alter_operatorprofessional_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='operator_professional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='professional_missions', to='professional.operatorprofessional', verbose_name='Profissional Alocado'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='operator_fleet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fleet_missions', to='professional.operatorfleet', verbose_name='Frota Alocada'),
        ),
    ]
