# Generated by Django 5.2.11 on 2026-02-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0003_mission_operator_professional_and_more'),
        ('professional', '0002_alter_operatorfleet_id_alter_operatorprofessional_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='operator_fleet',
        ),
        migrations.AddField(
            model_name='mission',
            name='operator_fleet',
            field=models.ManyToManyField(null=True, related_name='fleet_missions', to='professional.operatorfleet', verbose_name='Frota Alocada'),
        ),
    ]
