# Generated by Django 5.2.11 on 2026-02-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0004_remove_mission_operator_fleet_mission_operator_fleet'),
        ('professional', '0003_alter_operatorfleet_id_alter_operatorprofessional_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='operator_fleet',
            field=models.ManyToManyField(related_name='fleet_missions', to='professional.operatorfleet', verbose_name='Frota Alocada'),
        ),
    ]
