# Generated by Django 5.2.11 on 2026-02-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0005_alter_mission_id_alter_mission_operator_fleet'),
        ('professional', '0003_alter_operatorfleet_id_alter_operatorprofessional_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='operator_professional',
        ),
        migrations.AddField(
            model_name='mission',
            name='operator_professional',
            field=models.ManyToManyField(related_name='professional_missions', to='professional.operatorprofessional', verbose_name='Profissional Alocado'),
        ),
    ]
