# Generated by Django 5.2.11 on 2026-02-27 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0006_remove_mission_operator_professional_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['-mission_date'], 'verbose_name': 'Missão', 'verbose_name_plural': 'Missões'},
        ),
    ]
