# Generated by Django 5.2.11 on 2026-03-06 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0007_alter_mission_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['mission_date'], 'verbose_name': 'Missão', 'verbose_name_plural': 'Missões'},
        ),
    ]
